services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user 
      POSTGRES_DB: rejecct_url

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080